### ISSUE TITLE
Question: Render harp.gl earth in a-frame or threejs.

### ISSUE THREAD

**Issue by danielbeeke** [heremaps/harp.gl#1182]
Hello! 
Very awesome project!! I really like it!

I have been trying to get the globe of harp.gl and use it in a-frame (is also using threejs). 
Part of the project I am prototyping is a webvr with a globe with markers on it.

So far I found the threejs objects in mapView.worldRootObject. I saw a really big number for the size (something like 30000). I tried importing it into a a-frame component. Sort of works but I never see any object, but in the inspector it shows up.

I am wondering what I should do to import it into a-frame.

If this question is out of scope I would understand.
Thank you

**Comment by nzjony** [comment]
@danielbeeke , thanks for your comment.

**Comment by nzjony** [comment]
Sorry, I clicked "close and comment", instead of "comment.

**Comment by danielbeeke** [comment]
I will clean up my prototype this evening or tomorrow and send the link.

**Comment by danielbeeke** [comment]
The link to the repo: https://github.com/danielbeeke/WikiView/tree/master/prototypes

The question is about prototype 3. 

I try to start a harp.gl map and extract the 3D objects and put them into A-frame. You can see it in the file src/ts/AframeHarpGl.js.

The scene is loaded but you can not see the globe.

In prototype 4 you can see a little bit of what I am trying to do.

I try to create a web virtual reality where you can have the world in your hands, where markers of battles are placed on the world. 

The data is fetched from WikiData (Wikipedia etc).

**Comment by MPursche** [comment]
Hi @danielbeeke ,

I looked a bit into your code and if I understand it correctly you are creating a copy of `mapView.worldRootObject` and then add it to the A-Frame scene when the app is initialized?
I think this approach will not work with the way rendering is implemented in `MapView`.
The `MapView` class has it's own view frustum culling implementation apart from the culling implemented in THREE.js. Each time a frame is rendered `MapView` determines which parts of the globe(or map) are visible with the current camera setup and updates the children of `mapView.worldObject` accordingly.
I can think of two solutions to make your code work:
1. Add `mapView.worldObject` directly to the A-frame scene without creating a copy.
or
2. Update the globe in A-frame with the updated version of `mapView.worldObject` each time the camera in A-frame is updated.

Some additional things you need to take care of:
* The offscreen canvas that is used for `MapView` should have the same resolution as the canvas used for A-Frame(the zoom level of the map is dependent of the canvas resolution).
* The camera of A-Frame needs to be kept in sync with `mapView.camera` so the right parts of the globe are shown.
* Per default rendering in `MapView` is not synchronous. But synchronous rendering is supported as an option. This example [https://www.harp.gl/docs/master/examples/#rendering_synchronous.html](url) shows how to use `MapView` with synchronous rendering. This is important because the globe in A-Frame needs to be updated after the rendering of `MapView` has finished. Otherwise the scene is not updated correctly.
* The globe is pretty large so it may not be visible because the A-Frame camera is inside of the globe. The center of the globe is at [0,0,0] and one coordinate unit equals 1 meter. So the camera needs to be >6.371 km away from the center to be above the globes surface.
* The VR feature of A-Frame will probably not work correctly because it uses one camera per eye. So the `MapView` view frustum culling will not work out of the box. A combined eye frustum could be a workaround: [https://computergraphics.stackexchange.com/questions/1736/vr-and-frustum-culling](url). But the text labels and icons on the map will probably still not be rendered correctly in VR.

I hope I was able to help you to get your prototype working.

Kind regards

Marcel

**Comment by danielbeeke** [comment]
Hello Marcel,

Thank you for your reply!! I will try to make it work, thanks for the tips. If it works I will send a link.
Thanks again for the full explanation!

**Comment by trusktr** [comment]
I was also wondering about this. Basically harp.gl owns the camera and the scene, and does some custom stuff with it. Harp.gl isn't designed to have its content placed in any arbitrary scene.

Maybe to start helping with this use case, harp.gl could publish (maybe as events?) various info like camera position, frustum culling info, and any other info that it would normally have after user interaction, then it would be easier to consume that information, and for example, use our own camera and scene taking that information into account.

**Comment by nzjony** [comment]
@trusktr , you can specify a different point of view using the `pointOfView` getter/setter on the `MapView`, that means you can look at the scene however you like. We use it for example to debug the camera position in our internal test tool: 

![Screenshot 2020-03-09 at 10 12 30](https://user-images.githubusercontent.com/2533428/76198710-d745ad80-61ee-11ea-8a47-67f21518da08.png)

Would that help?

If you need other events, we could look to extend the `MapViewEventNames` enum, we have already events when the camera position changed, or when the viewport is resized. Do you have some concrete use case we could help you to solve?

**Comment by trusktr** [comment]
My use case is different: I have an existing Three.js application (a mapping application actually), but not on a global scale yet, and It'd be neat to be able to integrate the globe into my already-existing scene.

**Comment by trusktr** [comment]
Hmmm, I just thought of a possibly-neat idea (let me know if already possible):

- user picks a reference point in their scene, and assigns it a geo coordinate.
- any time they move the camera, they can get the offset and orientation of the camera relative to that point
- they can pass that to a Harp API
- Harp would take care to render the globe in the correct position, including with level of details based on camera distance from the globe, etc

That way, for example, in an outside Three.js-based app we could continue moving the camera in the non-Harp scene like before, then Harp would know how to manipulate the globe based on that camera.

Thoughts? Or is that too difficult with what Harp currently needs to do to the camera?

**Comment by nzjony** [comment]
@trusktr , have you seen the example: https://www.harp.gl/docs/master/examples/#getting-started_orbiting-view.html

The camera position is set using the `lookAt` method, see: https://www.harp.gl/docs/master/doc/classes/harp_mapview.mapview.html#lookat

Which takes the geo coordinate, height above ground, tilt and rotation and positions the camera, it should also work for globe too. The example ignores all user input.
