### ISSUE TITLE
Failed assertion in text rendering

### ISSUE THREAD

**Issue by Astrak** [heremaps/harp.gl#1285]
Hello harp team! The current master sometimes stalls when failing an assertion:
```
Uncaught Error: ASSERTION failed
    at Object.assert (assert.js:24)
    at TextElementStateCache.replaceElement (TextElementStateCache.js:257)
    at TextElementGroupState.traverseVisibleElements (TextElementGroupState.js:76)
    at TextElementStateCache.update (TextElementStateCache.js:186)
    at TextElementsRenderer.placeText (TextElementsRenderer.js:306)
    at MapView.prepareRenderTextElements (MapView.js:1974)
    at MapView.render (MapView.js:1864)
    at MapView.renderFunc (MapView.js:1724)
``` 
The corresponding code in TextElementStateCache.ts is:
```
replaceElement(zoomLevel, elementState) {
        assert(elementState.visible);
        const cacheResult = this.findDuplicate(elementState, zoomLevel);
        if (cacheResult === undefined || cacheResult.index === -1) {
            // No replacement found;
            return;
        }
        const replacement = cacheResult.entries[cacheResult.index];
        assert(!replacement.visible); // This is the assertion that sometimes fails.
        replacement.replace(elementState);
    }
```

Beyond the actual problem in the text rendering process, does the condition need an assertion that stops the app? Couldn't it just skip the following line instead?

**Comment by nzjony** [comment]
@atomicsulfate , can you take a look?

**Comment by atomicsulfate** [comment]
Hi @Astrak, thanks for reporting the issue. I'll create a bug ticket for it.

The assertion is there to catch a potential bug in the code. The function is looking for a potential replacement (i.e. a label corresponding to the  same map object but stored in a different tile) for a label that is gonna start to fade out because is not visited anymore (it's outside of view frustum or there was a zoom level change). Instead of fading out the first label, it's removed from the next frame and substituted by the replacement without fading transition. From the visual point of view, it's as if the label remains unchanged in the next frame.
As a precondition, the label replacement must not be visible yet, otherwise the labels wouldn't correspond to the same map object and cannot be handled jointly as if it was a single label.

In production code, the assertion is omitted and this particular bug won't lead to a crash.

We'll take a look as soon as possible. It would help if you could point out any location where it is triggered.

**Comment by kkostecki** [comment]
Bug ticket has been created HARP-8842.

We will update the status when it's done.
