### ISSUE TITLE
The model is clipped

### ISSUE THREAD

**Issue by PrUnSt** [heremaps/harp.gl#1573]
**Describe the bug**
The model is clipped in example （threejs_add-object.html）

**To Reproduce**
1. Zoom in
2. Right-click rotation
3. See error

![1](https://user-images.githubusercontent.com/30542005/83230591-95f4e680-a1bc-11ea-90cf-cbf582e895ff.png)

**Comment by nzjony** [comment]
@PrUnSt , this is because the camera near plane is too close.

I will create an internal task to ensure the near plane takes into consideration items added to the `mapAnchors`

**Comment by PrUnSt** [comment]
How can i create the object below the ground and only show the part on the ground

**Comment by nzjony** [comment]
@PrUnSt , in the example: https://www.harp.gl/docs/master/examples/#threejs_add-object.html

We set the `altitude` so:

`geoPosition.altitude = 50;` in: https://www.harp.gl/docs/master/examples/codebrowser.html?src=src%2Fthreejs_add-object.ts

Just set the altitude to 0 and half of it should be below the ground.

**Comment by PrUnSt** [comment]
i set geoPosition.altitude = 0; but It doesn't seem to be working
![1](https://user-images.githubusercontent.com/30542005/83253481-9e124d80-a1df-11ea-9ce8-cf4f0969cfa3.png)

**Comment by nzjony** [comment]
This is because we don't use the depth test when rendering the flat areas / streets, we just use the render order (and because they are flat, it mostly doesn't matter).

<img width="456" alt="Screenshot 2020-05-29 at 13 30 33" src="https://user-images.githubusercontent.com/2533428/83255428-b028c780-a1b0-11ea-8878-fe3d5a7903e4.png">

I did a test to confirm this by setting `material.depthTest = true` in the `createMaterial` function of `DecodedTileHelpers.ts` and got the image above which clips it correctly.

**Comment by nzjony** [comment]
Three.js has the idea of clipping planes, see: https://threejs.org/docs/#api/en/materials/Material.clippingPlanes

You could fake the cut by setting an appropriate clipping plane for the geometries material.
