### ISSUE TITLE
What is the best way to selectively remove buildings from the map?

### ISSUE THREAD

**Issue by harrycollin** [heremaps/harp.gl#1601]
I would like to be able to remove some buildings from the map and keep track of them for future use, for example: being able to remove them again after reloading based of an ID maybe. 

If we could target individual buildings then this would be great. I apologize in advance if this is already available. 

Thanks :)

**Comment by nzjony** [comment]
@harrycollin , thanks for the issue.

We don't support building IDs, because they were deemed to increase the tile size too much.

We do however support OSM via the XYZ service, and it has building IDs, you can test this by taking the example: https://www.harp.gl/docs/master/examples/#object-picking.html and then changing the data source to something like: 

```
const osmDataSource = new OmvDataSource({
    baseUrl: "https://xyz.api.here.com/tiles/osmbase/512/all",
    apiFormat: APIFormat.XYZMVT,
    styleSetName: "tilezen",
    maxZoomLevel: 17,
    authenticationCode: "YOUR_AUTH_CODE"
}); 
```

Where `YOUR_AUTH_CODE` is part of the access code you can get from xyz.here.com

We don't yet have a way to filter by ID, however it should be possible to modify the `OmvFeatureFilterDescriptionBuilder` class given a list of IDs

**Comment by harrycollin** [comment]
@nzjony Thank you! sorry for the late response on this, I was sure I'd replied here.

**Comment by nzjony** [comment]
@harrycollin , no worries.
