### ISSUE TITLE
Canvas data-source

### ISSUE THREAD

**Issue by jplante** [heremaps/harp.gl#1650]
**Is your feature request related to a problem? Please describe.**
We have our own proprietary data, as well as data that comes in GeoTiff format that we want to be able to write the rendering process for into a canvas and provide as a data source.  This allows us to provide advanced data visualization.  We'd rather not access and draw on top of the canvas element "owned" by the MapView.  Instead, we'd rather have a data source that is aware of another canvas and is able to grab the bitmap of that canvas and add it to its rendering. 

We are aware that we'd need to keep up with map context changes such as pitch, heading, bounds, level as the result of user interaction or programmatic changes.  We'd have to clear and repaint, and have some way to communicate for that data source the intended area to paint with regards to the map viewport.

**Describe the solution you'd like**
A new CanvasDataSource that could support drawing to a custom canvas, get added to the map view stack and permit updates.

Perhaps this already exists on a roadmap we are unaware of.

**Describe alternatives you've considered**
We've considered interfering with the rendering process or drawing directly to the canvas but would really rather not.

**Comment by nzjony** [comment]
hi @jplante, thanks for creating the issue.

Can you please elaborate a bit more about which use case you need to support? I take it that overlaying textures with alpha transparency isn't sufficient? It sounds like you want to take some data and modify the colors with some algorithm and then redisplay it?

The basic idea of a `DataSource` is that given a `TileKey` (which is simply a row, column, level), we return a list of objects to be drawn by three.js. I.e. the DataSource doesn't know where it will end up on screen. The `MapView` computes the list of visible tiles and we request those tiles from the `DataSource`s and they are then drawn from the perspective of the camera. You could theoretically pass in the canvas to the DataSource and it internally grabs the data there, but there is no guarantee that the requested tile is in view, for example, what do you do when you have a tile that is say 10% in view? You could wait until it comes into view, but that would look weird.

You will also have a lot of problems when tilting / rotating, because you will likely have aliasing problems at the edges also, and likely have some grid looking visual artifacts.

**Comment by FraukeF** [comment]
Hi jplante,

It is not planned at this point to add  a CanvasDatasource to harp.gl. I believe that the functionality you are looking for can be achieved without this datasource. 
Basically @here/harp-mapview/MapView should give you all necessary tools.
You can create your own canvas on top of the harp.gl canvas and listen to the MapView update event and then update your view depending on the current Map position, tilt, heading, fov...

**Comment by jplante** [comment]
Is the plan to move data-sources up and down the visible stack simply to "add" and "remove" them?  Wouldn't mind "canvas" be layered above the MapView and not able to be mixed in with the data-sources?

We want to be able to create all kinds of visualizations from all kinds of data sources (features, vectors, web tiles, custom raster, contours) etc and have them be able to be mixed and moved  up and down the stack between each other.

**Comment by nzjony** [comment]
@jplante , the order of the DataSources doesn't matter, what matters in the render order that is configured in the style, see: https://github.com/heremaps/harp.gl/blob/master/@here/harp-map-theme/resources/berlin_tilezen_base.json and search for `renderOrder`. 

The `MapView` iterates all `DataSource` and takes all `Objects` from the computed `Tile`s and adds them to the scene root node, see: https://github.com/heremaps/harp.gl/blob/18cd3da987dc499e868e6d0da36ac55242459e28/%40here/harp-mapview/lib/MapView.ts#L3646

I.e. three.js renders the objects based on the set `renderOrder`.

Or you can configure the renderOrder in the `DataSource` itself, see https://github.com/heremaps/harp.gl/blob/master/@here/harp-mapview/lib/BackgroundDataSource.ts and notice the call to `addGroundPlane` which passes in  `Number.MIN_SAFE_INTEGER`.

Did I understand your question correctly?

**Comment by jplante** [comment]
Yes you did thanks - and that's what i was hoping but for some reason i wasn't getting `renderOrder` to behave as I had expected.  I'll have to try again. 

However, still I'd like to have a canvas be mixed within the stack of items in that "renderOrder".  Does the rendeOrder map directly to z-index?

**Comment by nzjony** [comment]
@jplante , strange, yes, if you have some small example which shows the problem that would help.

There is a direct mapping except for the `extruded-polygon` technique, because all geometry is rendered without the depth test, at altitude 0, i.e. the geometry with the highest renderOrder is shown. However for the `extruded-polygon`, we use the depth buffer to ensure that they are drawn correctly.
