### ISSUE TITLE
GLTF API to load 3d model

### ISSUE THREAD

**Issue by sunyonglincanada** [heremaps/harp.gl#2086]
**Is your feature request related to a problem? Please describe.**
I was trying to load glb/gltf models in the project using harp.gl but found harp.gl is using FBXLoader to add 3D model for now.

**Describe the solution you'd like**
It would be great to have an API that allows us to load GLB/GLTF using Three.js GLTF loader through passing URL or the link from the local file system.

**Comment by nzjony** [comment]
@sunyonglincanada , see the PR I created: https://github.com/sunyonglincanada/harp.gl-GLTF/pull/1

It is quite simple to load the GLTF, at least much more simple than I thought it was. I still think we could make an API, but I don't think it is such a high priority because the current GLTFLoader class from three.js isn't too difficult to use.

**Comment by sunyonglincanada** [comment]
> @sunyonglincanada , see the PR I created: [sunyonglincanada/harp.gl-GLTF#1](https://github.com/sunyonglincanada/harp.gl-GLTF/pull/1)
> 
> It is quite simple to load the GLTF, at least much more simple than I thought it was. I still think we could make an API, but I don't think it is such a high priority because the current GLTFLoader class from three.js isn't too difficult to use.

Thanks @nzjony I've tried your method in the PR and it loads GLTF model properly. And yes, we will use this simple method for now to load GLTF models. It would be helpful if harp.gl supports the ability to have an API to load GLTF models and please keep me posted when it is available. Thanks so much for your notes and help!
