### ISSUE TITLE
Add more examples

### ISSUE THREAD

**Issue by burkoyuriy** [heremaps/harp.gl#2154]
Thanks for your work. A very interesting library.
Could you add more use cases if possible?
- Elevated geometries (lines, polygons) 
- Svg markers
- Dragging elements
- Dynamic styling

**Comment by nzjony** [comment]
hi @burkoyuriy , thanks for the feedback, we really appreciate people taking the time to comment.

What do you mean by elevated geometries? Do you want to have some lines / polygons overlaid on terrain? Or do you have some lines that have some elevation, such as the path of an aeroplane / satellite.

Regarding SVGs, we don't support this because we use an atlas when rendering the icons. i.e. we bake the SVG into an atlas file. But, for some special icons, we could consider to have SVGs.

Regarding dragging elements, what do you mean? Do you have some object that you want to, at the click of a button, pick up and move. This could be done on top of harp using a custom map object, but if there is enough demand, we could add some API.

Regarding dynamic styling, the functionality is available, just not for every parameter. We have an example where the colors change based on zoom, see: https://www.harp.gl/docs/master/examples/#styling_interpolation.html
Here: https://www.harp.gl/docs/master/examples/#datasource_geojson_styling_game.html is an example which shows a polygon being styled using `dynamic-properties`, these are values that you can changed in your application and are executed each frame before being rendered, hence `dynamic`
